<template>
  <div
    :class="[
      'flex',
      'flex-nowrap',
      'items-center',
      'justify-evenly',
      'w-full',
      'mt-[48px]',
      'md:w-min',
      'md:justify-start',
      'lg:mt-0',
    ]"
  >
    <Label
      :class="[
        'whitespace-nowrap',
        'text-medium-gray',
        'md:mr-[24px]',
      ]"
      :text="$t('HomePage.label.about')"
      preset="h6"
    />
    <Button
      class="md:mr-[24px]"
      preset="tertiary"
      text-preset="h6"
      size="mini"
      href="https://about.like.co/"
      :text="$t('HomePage.button.likecoin')"
    />
    <Button
      class="md:mr-[24px]"
      preset="tertiary"
      text-preset="h6"
      size="mini"
      href="https://medium.com/likecoin/proposal-to-fairdrop-likecoin-to-the-cosmos-community-and-civic-likers-d64d841287d8"
      :text="$t('HomePage.button.airdrop')"
    />
    <IconDot class="md:mr-[24px] lg:hidden"/>
    <Button
      class="lg:hidden"
      preset="tertiary"
      text-preset="h6"
      size="mini"
      href="https://go.crisp.chat/chat/embed/?website_id=5c009125-5863-4059-ba65-43f177ca33f7"
      :text="$t('HomePage.button.help')"
    />
  </div>
</template>

