<template>
  <div
    :class="[
      'flex',
      'flex-nowrap',
      'w-min',
    ]"
  >
    <Label
      :class="['whitespace-nowrap', 'mr-[24px]']"
      :text="$t('HomePage.label.about')"
      preset="h6"
    />
    <Button
      class="mr-[24px]"
      preset="tertiary"
      text-preset="h6"
      size="mini"
      href="https://about.like.co/"
      :text="$t('HomePage.button.likecoin')"
    />
    <Button
      class="mr-[24px]"
      preset="tertiary"
      text-preset="h6"
      size="mini"
      href="https://medium.com/likecoin/proposal-to-fairdrop-likecoin-to-the-cosmos-community-and-civic-likers-d64d841287d8"
      :text="$t('HomePage.button.airdrop')"
    />
  </div>
</template>

